export const mockUsers = [
  { id: "USR-001", name: "Rahul Sharma", email: "rahul@gmail.com", role: "Freelancer", status: "Active", trustScore: 82, verification: "Verified", riskLevel: "Low", joinDate: "Jan 12, 2025", lastActive: "2h ago", totalProjects: 14, totalSpent: null, totalEarned: 148000, aiFlag: false },
  { id: "USR-002", name: "Sneha Kapoor", email: "sneha@healthfirst.in", role: "Client", status: "Active", trustScore: 91, verification: "Verified", riskLevel: "Low", joinDate: "Feb 3, 2025", lastActive: "1d ago", totalProjects: 6, totalSpent: 320000, totalEarned: null, aiFlag: false },
  { id: "USR-003", name: "TechNova Solutions", email: "admin@technova.io", role: "Agency", status: "Active", trustScore: 74, verification: "Verified", riskLevel: "Medium", joinDate: "Mar 8, 2025", lastActive: "3h ago", totalProjects: 22, totalSpent: null, totalEarned: 890000, aiFlag: true },
  { id: "USR-004", name: "Vikram Singh", email: "vikram@shopeasey.com", role: "Client", status: "Active", trustScore: 55, verification: "Verified", riskLevel: "Medium", joinDate: "Nov 20, 2024", lastActive: "5d ago", totalProjects: 3, totalSpent: 280000, totalEarned: null, aiFlag: true },
  { id: "USR-005", name: "Priya Menon", email: "priya.m@freelance.com", role: "Freelancer", status: "Suspended", trustScore: 28, verification: "Verified", riskLevel: "High", joinDate: "Sep 1, 2024", lastActive: "15d ago", totalProjects: 4, totalSpent: null, totalEarned: 32000, aiFlag: true },
  { id: "USR-006", name: "Arjun Dev", email: "arjun@devcraft.io", role: "Freelancer", status: "Active", trustScore: 96, verification: "Verified", riskLevel: "Low", joinDate: "Apr 5, 2024", lastActive: "30m ago", totalProjects: 31, totalSpent: null, totalEarned: 560000, aiFlag: false },
  { id: "USR-007", name: "Meera Joshi", email: "meera@startup.co", role: "Client", status: "Pending", trustScore: 60, verification: "Unverified", riskLevel: "Medium", joinDate: "Mar 1, 2026", lastActive: "just now", totalProjects: 0, totalSpent: 0, totalEarned: null, aiFlag: false },
  { id: "USR-008", name: "BuildRight Agency", email: "ops@buildright.co", role: "Agency", status: "Active", trustScore: 88, verification: "Verified", riskLevel: "Low", joinDate: "Jul 14, 2024", lastActive: "1h ago", totalProjects: 18, totalSpent: null, totalEarned: 1200000, aiFlag: false },
  { id: "USR-009", name: "Karan Malhotra", email: "karan.m@tech.com", role: "Freelancer", status: "Active", trustScore: 71, verification: "Verified", riskLevel: "Low", joinDate: "Aug 22, 2024", lastActive: "4h ago", totalProjects: 9, totalSpent: null, totalEarned: 210000, aiFlag: false },
  { id: "USR-010", name: "FakeUser999", email: "fakeuser@temp.xyz", role: "Client", status: "Banned", trustScore: 10, verification: "Rejected", riskLevel: "High", joinDate: "Feb 28, 2026", lastActive: "8d ago", totalProjects: 1, totalSpent: 0, totalEarned: null, aiFlag: true },
];

export const mockFreelancers = [
  { id: "FL-001", name: "Rahul Sharma", email: "rahul@gmail.com", primarySkill: "React Developer", skillScore: 88, badge: "Pro+", trustScore: 82, activeProjects: 2, completedProjects: 12, disputeRate: "2%", onTimeDelivery: "94%", visibility: "Normal", riskFlag: "Low", joinDate: "Jan 12, 2025", totalEarned: 148000, responseTime: "2h", repeatHireRate: "45%", clientSentiment: 4.7, portfolio: ["github.com/rahuls", "rahuldesigns.io"], skills: ["React", "TypeScript", "Node.js", "Tailwind"], bio: "Full-stack developer with 4 years of experience building scalable web applications.", country: "India", timezone: "IST", availability: "40 hrs/week" },
  { id: "FL-002", name: "Arjun Dev", email: "arjun@devcraft.io", primarySkill: "Full Stack Engineer", skillScore: 96, badge: "Elite++", trustScore: 96, activeProjects: 3, completedProjects: 28, disputeRate: "0%", onTimeDelivery: "99%", visibility: "Boosted", riskFlag: "Low", joinDate: "Apr 5, 2024", totalEarned: 560000, responseTime: "45m", repeatHireRate: "78%", clientSentiment: 4.9, portfolio: ["github.com/arjundev"], skills: ["Django", "React", "PostgreSQL", "Redis", "AWS"], bio: "Senior full-stack engineer specialized in Django + React platforms.", country: "India", timezone: "IST", availability: "30 hrs/week" },
  { id: "FL-003", name: "Karan Malhotra", email: "karan.m@tech.com", primarySkill: "Mobile Developer", skillScore: 74, badge: "Verified", trustScore: 71, activeProjects: 1, completedProjects: 8, disputeRate: "8%", onTimeDelivery: "82%", visibility: "Normal", riskFlag: "Low", joinDate: "Aug 22, 2024", totalEarned: 210000, responseTime: "4h", repeatHireRate: "22%", clientSentiment: 4.1, portfolio: [], skills: ["Flutter", "Dart", "Firebase"], bio: "Mobile-first developer with 3 years in Flutter development.", country: "India", timezone: "IST", availability: "25 hrs/week" },
  { id: "FL-004", name: "Priya Menon", email: "priya.m@freelance.com", primarySkill: "UI/UX Designer", skillScore: 41, badge: "Verified", trustScore: 28, activeProjects: 0, completedProjects: 3, disputeRate: "32%", onTimeDelivery: "58%", visibility: "Reduced", riskFlag: "High", joinDate: "Sep 1, 2024", totalEarned: 32000, responseTime: "48h", repeatHireRate: "0%", clientSentiment: 2.3, portfolio: [], skills: ["Figma", "Adobe XD"], bio: "Designer focusing on mobile interfaces.", country: "India", timezone: "IST", availability: "20 hrs/week" },
  { id: "FL-005", name: "Neha Gupta", email: "neha@designcraft.in", primarySkill: "Graphic Designer", skillScore: 81, badge: "Pro+", trustScore: 79, activeProjects: 2, completedProjects: 17, disputeRate: "4%", onTimeDelivery: "90%", visibility: "Normal", riskFlag: "Low", joinDate: "Jun 10, 2024", totalEarned: 290000, responseTime: "1.5h", repeatHireRate: "55%", clientSentiment: 4.6, portfolio: ["behance.net/nehag"], skills: ["Figma", "Illustrator", "Photoshop", "Branding"], bio: "Brand identity designer with a strong portfolio in D2C and startups.", country: "India", timezone: "IST", availability: "35 hrs/week" },
];

export const mockAgencies = [
  { id: "AG-001", name: "TechNova Solutions", email: "admin@technova.io", legalName: "TechNova Pvt Ltd", country: "India", verificationStatus: "Verified", teamSize: 8, capabilityScore: 74, deliveryRisk: "Medium", activeProjects: 4, projectLimit: 6, trustScore: 74, overloadFlag: true, totalEarned: 890000, services: ["Web Development", "Mobile Apps", "Cloud"], industries: ["FinTech", "HealthTech"], joinDate: "Mar 8, 2025", website: "technova.io", adminName: "Raj Kumar", adminEmail: "raj@technova.io", kycStatus: "Verified", pendingPayouts: 125000, teamMembers: [{ name: "Raj Kumar", role: "Agency Admin", availability: 80, skills: ["Strategy", "PM"] }, { name: "Sara Patel", role: "Developer", availability: 60, skills: ["React", "Node"] }, { name: "Mike D", role: "Developer", availability: 70, skills: ["Django", "PostgreSQL"] }, { name: "Priya S.", role: "Designer", availability: 90, skills: ["Figma", "UI"] }] },
  { id: "AG-002", name: "BuildRight Agency", email: "ops@buildright.co", legalName: "BuildRight Technologies LLP", country: "India", verificationStatus: "Verified", teamSize: 15, capabilityScore: 88, deliveryRisk: "Low", activeProjects: 7, projectLimit: 12, trustScore: 88, overloadFlag: false, totalEarned: 1200000, services: ["Enterprise Software", "DevOps", "QA"], industries: ["E-Commerce", "Logistics"], joinDate: "Jul 14, 2024", website: "buildright.co", adminName: "Ananya Sharma", adminEmail: "ananya@buildright.co", kycStatus: "Verified", pendingPayouts: 340000, teamMembers: [{ name: "Ananya Sharma", role: "Agency Admin", availability: 100, skills: ["Operations", "BD"] }, { name: "Dev Team", role: "Developer", availability: 75, skills: ["Various"] }] },
  { id: "AG-003", name: "PixelCraft Studio", email: "hello@pixelcraft.design", legalName: "PixelCraft Design Studio", country: "India", verificationStatus: "Pending", teamSize: 4, capabilityScore: 62, deliveryRisk: "Medium", activeProjects: 2, projectLimit: 3, trustScore: 62, overloadFlag: false, totalEarned: 180000, services: ["UI/UX Design", "Branding"], industries: ["Startups", "D2C"], joinDate: "Jan 5, 2026", website: "pixelcraft.design", adminName: "Rohan Mehta", adminEmail: "rohan@pixelcraft.design", kycStatus: "Pending", pendingPayouts: 45000, teamMembers: [] },
];

export const mockClients = [
  { id: "CL-001", name: "Sneha Kapoor", email: "sneha@healthfirst.in", company: "HealthFirst Clinic", clientType: "Startup", country: "India", trustScore: 91, verificationStatus: "Verified", totalProjects: 6, totalSpent: 320000, activeProjects: 1, disputeInitiationRate: "0%", paymentReliability: "Excellent", scopeChangeFreq: "Low", riskLevel: "Low", joinDate: "Feb 3, 2025", preferredCurrency: "INR", billingAddress: "Mumbai, India", escrowLocked: 120000, refundHistory: [], warnings: 0, aiFlag: false },
  { id: "CL-002", name: "Vikram Singh", email: "vikram@shopeasy.com", company: "ShopEasy Retail", clientType: "Enterprise", country: "India", trustScore: 55, verificationStatus: "Verified", totalProjects: 3, totalSpent: 280000, activeProjects: 1, disputeInitiationRate: "33%", paymentReliability: "Average", scopeChangeFreq: "High", riskLevel: "Medium", joinDate: "Nov 20, 2024", preferredCurrency: "INR", billingAddress: "Delhi, India", escrowLocked: 80000, refundHistory: [{ date: "Jan 2025", amount: 40000, reason: "Scope dispute" }], warnings: 2, aiFlag: true },
  { id: "CL-003", name: "Meera Joshi", email: "meera@startup.co", company: null, clientType: "Individual", country: "India", trustScore: 60, verificationStatus: "Unverified", totalProjects: 0, totalSpent: 0, activeProjects: 0, disputeInitiationRate: "N/A", paymentReliability: "Unknown", scopeChangeFreq: "N/A", riskLevel: "Medium", joinDate: "Mar 1, 2026", preferredCurrency: "INR", billingAddress: "", escrowLocked: 0, refundHistory: [], warnings: 0, aiFlag: false },
  { id: "CL-004", name: "ByteEats Co.", email: "projects@byteeats.in", company: "ByteEats Technologies", clientType: "Startup", country: "India", trustScore: 84, verificationStatus: "Verified", totalProjects: 4, totalSpent: 650000, activeProjects: 2, disputeInitiationRate: "0%", paymentReliability: "Excellent", scopeChangeFreq: "Low", riskLevel: "Low", joinDate: "Oct 11, 2024", preferredCurrency: "INR", billingAddress: "Bangalore, India", escrowLocked: 280000, refundHistory: [], warnings: 0, aiFlag: false },
  { id: "CL-005", name: "FakeUser999", email: "fakeuser@temp.xyz", company: null, clientType: "Individual", country: "Unknown", trustScore: 10, verificationStatus: "Rejected", totalProjects: 1, totalSpent: 0, activeProjects: 0, disputeInitiationRate: "100%", paymentReliability: "Poor", scopeChangeFreq: "High", riskLevel: "High", joinDate: "Feb 28, 2026", preferredCurrency: "INR", billingAddress: "", escrowLocked: 0, refundHistory: [], warnings: 3, aiFlag: true },
];